namespace: "mmas"
name: "nginx"
description: Ansible modules for NGINX
authors:
  - "Modesto Mas"
version: "0.0.1"
license:
  - "MIT"
tags:
  - nginx
  - reverse_proxy
  - load_balancer
readme: "README.md"
repository: "https://github.com/mmas/nginx-ansible-collection"
issues: "https://github.com/mmas/nginx-ansible-collection/issues"
